# Generated by Django 6.0.6 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('tours', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('hide_tour', 'Скрыть тур'), ('unhide_tour', 'Снять скрытие'), ('delete_tour', 'Удалить тур'), ('block_provider', 'Заблокировать исполнителя'), ('unblock_provider', 'Разблокировать исполнителя'), ('approve_verification', 'Одобрить верификацию'), ('reject_verification', 'Отклонить верификацию')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, db_column='admin_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='users.user')),
                ('target_provider_profile', models.ForeignKey(blank=True, db_column='target_provider_profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.providerprofile')),
                ('target_tour', models.ForeignKey(blank=True, db_column='target_tour_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Действие модерации',
                'verbose_name_plural': 'Журнал модерации',
                'db_table': 'moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
