# Generated by Django 6.0.6 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'db_table': 'difficulty_levels',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('icon', models.CharField(blank=True, max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тип тура',
                'verbose_name_plural': 'Типы туров',
                'db_table': 'tour_types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На проверке'), ('published', 'Опубликован'), ('hidden', 'Скрыт'), ('archived', 'В архиве')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty_level', models.ForeignKey(db_column='difficulty_level_id', on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.difficultylevel')),
                ('provider_profile', models.ForeignKey(db_column='provider_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='providers.providerprofile')),
                ('tour_type', models.ForeignKey(db_column='tour_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.tourtype')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'db_table': 'tours',
            },
        ),
        migrations.CreateModel(
            name='TourInsuranceDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_insurance_required', models.BooleanField(default=True)),
                ('min_medical_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medical_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('requires_evacuation', models.BooleanField(default=False)),
                ('min_evacuation_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evacuation_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('notes_ru', models.TextField(blank=True, null=True)),
                ('notes_en', models.TextField(blank=True, null=True)),
                ('tour', models.OneToOneField(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_details', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Страховые детали тура',
                'verbose_name_plural': 'Страховые детали туров',
                'db_table': 'tour_insurance_details',
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Фото тура',
                'verbose_name_plural': 'Фотографии туров',
                'db_table': 'tour_photos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TourVisaDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requires_border_permit', models.BooleanField(default=False)),
                ('requires_special_permit', models.BooleanField(default=False)),
                ('notes_ru', models.TextField(blank=True, null=True)),
                ('notes_en', models.TextField(blank=True, null=True)),
                ('tour', models.OneToOneField(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='visa_details', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Визовые детали тура',
                'verbose_name_plural': 'Визовые детали туров',
                'db_table': 'tour_visa_details',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevelTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty_level', models.ForeignKey(db_column='difficulty_level_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.difficultylevel')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
            ],
            options={
                'verbose_name': 'Перевод уровня сложности',
                'verbose_name_plural': 'Переводы уровней сложности',
                'db_table': 'difficulty_level_translations',
                'unique_together': {('difficulty_level', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TourRoutePoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveSmallIntegerField()),
                ('day_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('notes_en', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='route_points', to='locations.location')),
                ('tour', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрутов',
                'db_table': 'tour_route_points',
                'ordering': ['sequence_order'],
                'unique_together': {('tour', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='TourTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('route_overview', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
                ('tour', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Перевод тура',
                'verbose_name_plural': 'Переводы туров',
                'db_table': 'tour_translations',
                'unique_together': {('tour', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TourTypeTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
                ('tour_type', models.ForeignKey(db_column='tour_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tours.tourtype')),
            ],
            options={
                'verbose_name': 'Перевод типа тура',
                'verbose_name_plural': 'Переводы типов туров',
                'db_table': 'tour_type_translations',
                'unique_together': {('tour_type', 'language')},
            },
        ),
    ]
