# Generated by Django 6.0.6 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtranslation',
            name='is_auto_translated',
            field=models.BooleanField(default=False),
        ),
    ]
