# Generated by Django 6.0.6 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория справки',
                'verbose_name_plural': 'Категории справки',
                'db_table': 'help_categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_admin', models.ForeignKey(blank=True, db_column='author_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='users.user')),
                ('help_category', models.ForeignKey(db_column='help_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='helpdesk.helpcategory')),
            ],
            options={
                'verbose_name': 'Статья справки',
                'verbose_name_plural': 'Статьи справки',
                'db_table': 'help_articles',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticleTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('help_article', models.ForeignKey(db_column='help_article_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='helpdesk.helparticle')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
            ],
            options={
                'verbose_name': 'Перевод статьи справки',
                'verbose_name_plural': 'Переводы статей справки',
                'db_table': 'help_article_translations',
                'unique_together': {('help_article', 'language')},
            },
        ),
        migrations.CreateModel(
            name='HelpCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('help_category', models.ForeignKey(db_column='help_category_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='helpdesk.helpcategory')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
            ],
            options={
                'verbose_name': 'Перевод категории справки',
                'verbose_name_plural': 'Переводы категорий справки',
                'db_table': 'help_category_translations',
                'unique_together': {('help_category', 'language')},
            },
        ),
    ]
