# Generated by Django 6.0.6 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iso_alpha2', models.CharField(max_length=2, unique=True)),
                ('iso_alpha3', models.CharField(max_length=3, unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('applies_to', models.CharField(choices=[('general', 'Общее'), ('mountain', 'Горный маршрут'), ('custom', 'Особое')], default='general', max_length=10)),
                ('min_medical_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medical_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('requires_evacuation', models.BooleanField(default=False)),
                ('min_evacuation_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evacuation_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Требование к страхованию',
                'verbose_name_plural': 'Требования к страхованию',
                'db_table': 'insurance_requirements',
            },
        ),
        migrations.CreateModel(
            name='VisaPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('max_stay_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rolling_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_evisa', models.BooleanField(default=False)),
                ('evisa_portal_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_eaeu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Визовый режим',
                'verbose_name_plural': 'Визовые режимы',
                'db_table': 'visa_policies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceRequirementTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('insurance_requirement', models.ForeignKey(db_column='insurance_requirement_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visas.insurancerequirement')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
            ],
            options={
                'verbose_name': 'Перевод требования к страхованию',
                'verbose_name_plural': 'Переводы требований к страхованию',
                'db_table': 'insurance_requirement_translations',
                'unique_together': {('insurance_requirement', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CountryVisaPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='visa_policies', to='visas.country')),
                ('visa_policy', models.ForeignKey(db_column='visa_policy_id', on_delete=django.db.models.deletion.PROTECT, related_name='country_links', to='visas.visapolicy')),
            ],
            options={
                'verbose_name': 'Визовый режим страны',
                'verbose_name_plural': 'Визовые режимы стран',
                'db_table': 'country_visa_policies',
                'unique_together': {('country', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='VisaPolicyTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
                ('visa_policy', models.ForeignKey(db_column='visa_policy_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='visas.visapolicy')),
            ],
            options={
                'verbose_name': 'Перевод визового режима',
                'verbose_name_plural': 'Переводы визовых режимов',
                'db_table': 'visa_policy_translations',
                'unique_together': {('visa_policy', 'language')},
            },
        ),
    ]
