# Generated by Django 6.0.6 on 2026-06-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип сертификата',
                'verbose_name_plural': 'Типы сертификатов',
                'db_table': 'certificate_types',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocumentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_ru', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Тип документа верификации',
                'verbose_name_plural': 'Типы документов верификации',
                'db_table': 'verification_document_types',
            },
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ru', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Статус верификации',
                'verbose_name_plural': 'Статусы верификации',
                'db_table': 'verification_statuses',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('avatar_path', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='users.user')),
                ('verification_status', models.ForeignKey(db_column='verification_status_id', on_delete=django.db.models.deletion.PROTECT, related_name='provider_profiles', to='providers.verificationstatus')),
            ],
            options={
                'verbose_name': 'Профиль исполнителя',
                'verbose_name_plural': 'Профили исполнителей',
                'db_table': 'provider_profiles',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_type', models.ForeignKey(blank=True, db_column='certificate_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.certificatetype')),
                ('provider_profile', models.ForeignKey(db_column='provider_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('provider_profile', models.ForeignKey(db_column='provider_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='providers.providerprofile')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, db_column='reviewed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to='users.user')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='providers.verificationstatus')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
                'db_table': 'verification_requests',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.PROTECT, to='providers.verificationdocumenttype')),
                ('verification_request', models.ForeignKey(db_column='verification_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='providers.verificationrequest')),
            ],
            options={
                'verbose_name': 'Документ верификации',
                'verbose_name_plural': 'Документы верификации',
                'db_table': 'verification_documents',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfileTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.PROTECT, to='core.language')),
                ('provider_profile', models.ForeignKey(db_column='provider_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='providers.providerprofile')),
            ],
            options={
                'verbose_name': 'Перевод профиля исполнителя',
                'verbose_name_plural': 'Переводы профилей исполнителей',
                'db_table': 'provider_profile_translations',
                'unique_together': {('provider_profile', 'language')},
            },
        ),
    ]
